sudo: required
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
    - PGPORT=5433
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - postgresql
  - rabbitmq
install:
  - pip install -r requirements.txt
  - pip install codecov
before_script:
  - psql --command "CREATE DATABASE saltant;"
  - psql --command "CREATE USER johnsmith WITH PASSWORD 'johnsmithspassword';"
  - psql --command "ALTER ROLE johnsmith SET client_encoding TO 'utf8';"
  - psql --command "ALTER ROLE johnsmith SET default_transaction_isolation TO 'read committed';"
  - psql --command "ALTER ROLE johnsmith SET timezone TO 'UTC';"
  - psql --command "GRANT ALL PRIVILEGES ON DATABASE saltant TO johnsmith;"
  - psql --command "ALTER USER johnsmith CREATEDB;"
script:
  - cp .env.example .env
  - ./manage.py check
  - ./manage.py migrate
  - ./manage.py test
after_success:
  - codecov
